const moviesData = [
    {
        id: Math.random(),
        image: "https://i2.wp.com/smallthings.fr/wp-content/uploads/2021/04/godzilla-vs-kong-critique.jpg",
        rating: 3,
        name: "Godzilla vs. Kong",
        date: "2021",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://www.uphe.com/sites/default/files/styles/scale__344w_/public/2021/03/Dara.jpg",
        rating: 4,
        name: "Dara of Jasenovac",
        date: "2021",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },

    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/076768ed9134955a90200bfc8622cbe7/4dcf5ab4-d2af-4421-983c-ad319da6b754.jpg?h=375&resize=fit&w=250",
        rating: 2,
        name: "Joker",
        date: "2019",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/83dbddac259a1bd245f4ab002ef7186a/b4d369b0-c3fb-4097-8520-aef9ab3826ed.jpg?h=375&resize=fit&w=250",
        rating: 4,
        name: "Trolls",
        date: "2016",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/457e3fa36b7131aef0901391b3a18cc4/cc066f54-70e9-4aae-ba4d-daece072706f.jpg?h=375&resize=fit&w=250",
        rating: 4,
        name: "Star wars",
        date: "1983",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/47295f8b80c9634dad7aa8d306ff7da2/0f87b7f6-ff62-469f-b0d4-d47d72150ec1.jpg?h=375&resize=fit&w=250",
        rating: 4,
        name: "X-Men : First Class",
        date: "2011",
        description:"In 1944, at the Auschwitz concentration camp, Nazi officer Klaus Schmidt witnesses young prisoner Erik Lehnsherr bend a metal gate with his mind upon being separated from his mother. In his office, Schmidt orders Erik to move a coin on his desk, and kills the boy's mother when Erik cannot. In grief and anger, Erik's magnetic power manifests, killing two guards and destroying the room. Meanwhile, at a mansion in Westchester County, New York, child telepath Charles Xavier meets young shapeshifter Raven, whose natural form is blue-skinned and scaly. Overjoyed to meet someone different, like himself, he invites her to live with his family as his foster sister.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/d2c6e9c510b22933e69ca30f8ec6f5a3/4e9d04e3-787e-41bf-aaaf-98a78d5c9f9d.jpg?h=375&resize=fit&w=250",
        rating: 4,
        name: "Thor",
        date: "2011",
        description:"In Germanic mythology, Thor (/θɔːr/; from Old Norse: Þórr) is a hammer-wielding god associated with lightning, thunder, storms, sacred groves and trees, strength, the protection of mankind and also hallowing and fertility. Besides Old Norse Þórr, the deity occurs in Old English as Þunor, in Old Frisian as Thuner, in Old Saxon as Thunar, and in Old High German as Donar, all ultimately stemming from the Proto-Germanic theonym *Þun(a)raz, meaning 'Thunder'.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
    {
        id: Math.random(),
        image: "https://images.moviesanywhere.com/d4d5e4832edbfddce039d987fb46e25e/56110830-a52c-4aa1-a81e-71f5925b02b5.jpg?h=375&resize=fit&w=250",
        rating: 4,
        name: "Jojo Rabbit",
        date: "2019",
        description:"Jojo Rabbit is a 2019 comedy-drama film written and directed by Taika Waititi, adapted from Christine Leunens's 2008 book Caging Skies. Roman Griffin Davis portrays the title character, Johannes Jojo Betzler, a ten-year-old Hitler Youth member who finds out that his mother (Scarlett Johansson) is hiding a Jewish girl (Thomasin McKenzie) in their attic. He must then question his beliefs while dealing with the intervention of his imaginary friend (Waititi), a fanciful version of Adolf Hitler with a comedic stance on the politics of the war. The film also stars Sam Rockwell, Rebel Wilson, Stephen Merchant and Alfie Allen.",
        trailer:"https://www.youtube.com/watch?v=tL4McUzXfFI",
    },
];

export default moviesData;